[package]
name = "fi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
humansize = "2.1.3"
jwalk = "0.8.1"
prettytable-rs = "0.10.0"
spinners = "4.1.1"
thousands = "0.2.0"
